version: "3.8"

services:
  product_db:
    image: postgres:15-alpine
    container_name: product_db_container
    restart: always
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" # host:container
    volumes:
      - product_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d products"]
      interval: 5s
      timeout: 5s
      retries: 10

  order_db:
    image: postgres:15-alpine
    container_name: order_db_container
    restart: always
    environment:
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders"]
      interval: 5s
      timeout: 5s
      retries: 10

  customer_db:
    image: postgres:15-alpine
    container_name: customer_db_container
    restart: always
    environment:
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - customer_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d customers"]
      interval: 5s
      timeout: 5s
      retries: 10

  product_service:
    build:
      context: ./backend/product_service
      dockerfile: Dockerfile
    image: local/product_service:dev
    container_name: product_api_container
    restart: always
    ports:
      - "8000:8000"
    environment:
      POSTGRES_HOST: product_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: products
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      AZURE_STORAGE_ACCOUNT_NAME: <your_storage_account_name>
      AZURE_STORAGE_ACCOUNT_KEY: <your_storage_account_key>
      AZURE_STORAGE_CONTAINER_NAME: <your_container_name>
      AZURE_SAS_TOKEN_EXPIRY_HOURS: 24
    depends_on:
      product_db:
        condition: service_healthy
    volumes:
      - ./backend/product_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  order_service:
    build:
      context: ./backend/order_service
    image: local/order_service:dev
    container_name: order_api_container
    restart: always
    ports:
      - "8001:8000"
    environment:
      POSTGRES_HOST: order_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PRODUCT_SERVICE_URL: http://product_service:8000
      CUSTOMER_SERVICE_URL: http://customer_service:8000
    depends_on:
      order_db:
        condition: service_healthy
      product_service:
        condition: service_started
    volumes:
      - ./backend/order_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  customer_service:
    build:
      context: ./backend/customer_service
    image: local/customer_service:dev
    container_name: customer_api_container
    restart: always
    ports:
      - "8002:8000"
    environment:
      POSTGRES_HOST: customer_db
      POSTGRES_PORT: 5432
      POSTGRES_DB: customers
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    depends_on:
      customer_db:
        condition: service_healthy
    volumes:
      - ./backend/customer_service/app:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: local/frontend:dev
    container_name: ecommerce_frontend
    restart: always
    ports:
      - "3000:80" # browse http://localhost:3000
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    depends_on:
      product_service:
        condition: service_started
      order_service:
        condition: service_started
      customer_service:
        condition: service_started

# Volumes
volumes:
  product_db_data:
  order_db_data:
  customer_db_data:
