apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service-w10t2
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
      - name: customer-service-container
        image: poojadissanayake.azurecr.io/customer_service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        # Database connection details
        - name: POSTGRES_HOST
          value: product-db-service-w10t2
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config-w10t2
              key: PRODUCTS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret-w10t2 
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret-w10t2
              key: POSTGRES_PASSWORD
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret-w10t2 
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: ecommerce-secret-w10t2
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config-w10t2 
              key: AZURE_STORAGE_CONTAINER_NAME
        - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
          valueFrom:
            configMapKeyRef:
              name: ecommerce-config-w10t2
              key: AZURE_SAS_TOKEN_EXPIRY_HOURS
---
apiVersion: v1
kind: Service
metadata:
  name: customer-service-w10t2
  labels:
    app: customer-service
spec:
  selector:
    app: customer-service
  ports:
    - protocol: TCP
      port: 8003
      targetPort: 8000
  type: LoadBalancer