apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-w10t2
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: poojadissanayake.azurecr.io/order_service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8001
          env:
            - name: POSTGRES_HOST
              value: order-db-service-w10t2
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: ORDER_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_PASSWORD
            - name: PRODUCT_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: PRODUCT_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-w10t2
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  type: LoadBalancer
  ports:
    - name: http
      port: 8001
      targetPort: 8001
