apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-w10t2
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service-container
          image: poojadissanayake.azurecr.io/product_service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_HOST
              value: product-db-service-w10t2
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: PRODUCTS_DB_NAME
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: POSTGRES_PASSWORD

            # Azure Blob Storage (created by pipeline secret 'ecommerce-secret-w10t2')
            - name: AZURE_STORAGE_ACCOUNT_NAME
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: AZURE_STORAGE_ACCOUNT_NAME
            - name: AZURE_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: ecommerce-secret-w10t2
                  key: AZURE_STORAGE_ACCOUNT_KEY

            - name: AZURE_STORAGE_CONTAINER_NAME
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: AZURE_STORAGE_CONTAINER_NAME
            - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
              valueFrom:
                configMapKeyRef:
                  name: ecommerce-config-w10t2
                  key: AZURE_SAS_TOKEN_EXPIRY_HOURS
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-w10t2
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
