name: CD - Deploy to Staging

on:
  workflow_run:
    workflows: ["Frontend CI - Build & Push Image"]
    types:
      - completed

jobs:
  deploy_backend:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/backend_cd.yml
    with:
      aks_cluster_name: ${{ vars.AKS_CLUSTER_NAME }}
      aks_resource_group: ${{ vars.AKS_RESOURCE_GROUP }}
    secrets: inherit

  acceptance_tests:
    needs: deploy_backend
    runs-on: ubuntu-latest
    steps:
      - name: Health checks
        run: |
          echo "Checking Product: ${{ needs.deploy_backend.outputs.PRODUCT_IP }}:8000"
          for i in {1..30}; do
          if curl -s --fail http://${{ needs.deploy_backend.outputs.PRODUCT_IP }}:8000/health; then
              echo "Product service healthy"
              break
          fi
          echo "Waiting for Product service... attempt $i"
          sleep 10
          done

          echo "Checking Order: ${{ needs.deploy_backend.outputs.ORDER_IP }}:8001"
          for i in {1..30}; do
          if curl -s --fail http://${{ needs.deploy_backend.outputs.ORDER_IP }}:8001/health; then
              echo "Order service healthy"
              break
          fi
          echo "Waiting for Order service... attempt $i"
          sleep 10
          done

          echo "Checking Customer: ${{ needs.deploy_backend.outputs.CUSTOMER_IP }}:8002"
          for i in {1..30}; do
          if curl -s --fail http://${{ needs.deploy_backend.outputs.CUSTOMER_IP }}:8002/health; then
              echo "Customer service healthy"
              break
          fi
          echo "Waiting for Customer service... attempt $i"
          sleep 10
          done

  deploy_frontend:
    needs: [acceptance_tests, deploy_backend]
    uses: ./.github/workflows/frontend_cd.yml
    with:
      product_api_url: http://${{ needs.deploy_backend.outputs.PRODUCT_IP }}:8000
      order_api_url: http://${{ needs.deploy_backend.outputs.ORDER_IP }}:8001
      customer_api_url: http://${{ needs.deploy_backend.outputs.CUSTOMER_IP }}:8002
    secrets: inherit
