name: CD - Staging (Deploy & Test)

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Backend CI - Test, Build and Push Images to ACR", "Frontend CI - Build & Push Image"]
    types: 
       - completed
    branches: 
        - testing

jobs:
  # Deploy all backend services and expose their IPs as outputs
  deploy_backend:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/backend_cd.yml
    with:
      aks_cluster_name:   ${{ vars.AKS_CLUSTER_NAME }}
      aks_resource_group: ${{ vars.AKS_RESOURCE_GROUP }}
    secrets: inherit   

  # Quick acceptance checks before deploying frontend
  acceptance_tests:
    needs: deploy_backend
    runs-on: ubuntu-latest
    steps:
      - name: Health checks
        run: |
          echo "Product IP:  ${{ needs.deploy_backend.outputs.PRODUCT_API_IP }}"
          echo "Order IP:    ${{ needs.deploy_backend.outputs.ORDER_API_IP }}"
          echo "Customer IP: ${{ needs.deploy_backend.outputs.CUSTOMER_API_IP }}"
          curl --fail "http://${{ needs.deploy_backend.outputs.PRODUCT_API_IP }}:8000/health"
          curl --fail "http://${{ needs.deploy_backend.outputs.ORDER_API_IP }}:8001/health"
          curl --fail "http://${{ needs.deploy_backend.outputs.CUSTOMER_API_IP }}:8002/health"

  # Deploy frontend using the backend IPs
  deploy_frontend:
    needs: acceptance_tests
    uses: ./.github/workflows/frontend_cd.yml
    with:
      product_api_ip:   http://${{ needs.deploy_backend.outputs.PRODUCT_API_IP }}:8000
      order_api_ip:     http://${{ needs.deploy_backend.outputs.ORDER_API_IP }}:8001
      customer_api_ip:  http://${{ needs.deploy_backend.outputs.CUSTOMER_API_IP }}:8002
      aks_cluster_name:   ${{ vars.AKS_CLUSTER_NAME }}
      aks_resource_group: ${{ vars.AKS_RESOURCE_GROUP }}
    secrets: inherit